apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: epwt9pj83-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-ad656543dc.xwcg.p3.openshiftapps.com/rhtap/rhtap-qe:16126acb50de5462b814e5323093153cb11089c1@sha256:761e041fc26b4f3ad1651c993c47bc23430684f9820cbdba61d4c2ac2db7e0eb
          name: container-image
