apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: epwt9pj83-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: epwt9pj83-python 
  name: epwt9pj83-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: epwt9pj83-python 
